services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080/tcp
    environment:
      #To ensure that the correct user has access
      - PUID=${PUID}
      - PGID=${PGID}
      # Windscribe specific Setup over WireGuard
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${VPN_ADDRESS}
      - WIREGUARD_PRESHARED_KEY=${PRESHARED_KEY}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_CITIES=${SERVER_CITIES}
      - FIREWALL_VPN_INPUT_PORTS=${VPN_PORTS}
      - UPDATER_PERIOD=24h
    volumes:
      - ${CONFIG_PATH}/gluetun:/gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
